[package]
name = "example-wasm"
authors.workspace = true
edition.workspace = true
keywords.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
wasmparser = "0.244.0"
sljit = { path = ".." }
libm = "0.2"
indexmap = "2.13.0"
